// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import SideNavbar from '@/components/global/SideNavbar';
import Header from '@/components/global/Header';
import { SidebarProvider } from '@/contexts/SidebarContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
