// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import SideNavbar from '@/components/global/SideNavbar';
import Header from '@/components/global/Header';
import { SidebarProvider } from '@/contexts/SidebarContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary flex w-full">
        <SidebarProvider>
          <div className="flex flex-col flex-1">
            <div>
              <Header />
            </div>
            <div className="flex flex-row">
              <div className="w-1/7">
                <SideNavbar />
              </div>
              <div className="w-6/7">{children}</div>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
